[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["pollution/data"]
  data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "pollution"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "pm25"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "pm10"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "no2"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "o3"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "co"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "temperature"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "humidity"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "lat"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "lon"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "sensor_id"


[[outputs.influxdb_v3]]
  urls = ["http://influxdb:8181"]
  token = "${INFLUXDB_TOKEN}"
  database = "iot_data"
